import base64
import csv
import hashlib
import io
import os
import shutil
import stat
import sys
import sysconfig
import zipfile
from pathlib import Path

from setuptools import setup

try:
    from pybind11.setup_helpers import Pybind11Extension, build_ext as _pybind11_build_ext
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pybind11"])
    from pybind11.setup_helpers import Pybind11Extension, build_ext as _pybind11_build_ext

try:
    from setuptools.command.bdist_wheel import bdist_wheel as _bdist_wheel
except ImportError:  # setuptools < 70.1 -- bdist_wheel was still the separate `wheel` package
    try:
        from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    except ImportError:
        _bdist_wheel = None

_IS_MSVC = sys.platform == "win32"  # this project only ever builds Windows wheels with MSVC

ext_modules = [
    Pybind11Extension(
        "aether_core",
        [
            "src/core.cpp",
            "src/sha256.cpp",
            "src/sha256_backend.cpp",
            "src/sha256_shani.cpp",
            "src/sha256_arm.cpp",
        ],
        include_dirs=["src/"],
        cxx_std=17,
        # Deliberately never -march=native: a wheel is built once and installed on machines
        # whose exact CPU is unknown, so hardware-specific acceleration (x86 SHA-NI) is
        # runtime-dispatched (sha256_backend.cpp, gated per-function via GCC/Clang's
        # __attribute__((target(...))), needing no extension-wide flag at all) rather than
        # baked in at compile time. sha256_arm.cpp is capability-detection-only for now (see
        # that file) and needs no special flag yet either; a real ARM64 crypto kernel will
        # need one when it lands, since AArch64 GCC/Clang lack a portable per-function
        # target-attribute equivalent to x86's -- tracked alongside that follow-up work.
        extra_compile_args=["/O2"] if _IS_MSVC else ["-O3"],
    ),
]

# V1.6.0: the native `av` launcher. `av` is injected directly into the built WHEEL's
# `.data/scripts/` by `WheelWithNativeLauncher` below -- NOT via setuptools' own `scripts=`/
# `distribution.scripts` machinery, which a real attempt this session proved is a HARD BUILD
# BREAK on this toolchain: setuptools' vendored `build_scripts` command calls
# `tokenize.open()` unconditionally on every `scripts=` entry to sniff a shebang line, which
# raises `SyntaxError: source code cannot contain null bytes` on any raw binary executable,
# failing `python -m build --wheel` outright (confirmed live, not theorized). Post-processing
# the already-built wheel bypasses that command entirely. See pyproject.toml's comment on
# `av-py` and src/launcher/README.md's Packaging section for the full account, including why
# pip's OWN installer is safe for this (its `fix_script()` opens in binary mode and only acts
# on a literal `#!python` first line -- verified by reading
# `pip._internal.operations.install.wheel` directly).
_PY_SHIM = (
    "#!python\n"
    "# Auto-generated by setup.py when the native av launcher wasn't built for this "
    "platform/toolchain -- functionally identical to av-py, just without the native-exe "
    "speed win. See src/launcher/README.md.\n"
    "from av_cli.launcher import main\n"
    "if __name__ == \"__main__\":\n"
    "    main()\n"
)


class BuildExtWithLauncher(_pybind11_build_ext):
    """Compiles the native launcher (Windows and POSIX -- see src/launcher/README.md for
    which parts of the POSIX side are CI-verified rather than verified on this project's
    own dev box) and records what `WheelWithNativeLauncher` should inject as `av` in
    `self.distribution.av_launcher_artifact = (arcname, source_path, is_binary)` -- ALWAYS
    set, on every platform and even on a build failure, so a wheel never ends up with no
    `av` command at all: a successful native build records the real exe (arcname "av.exe"
    on Windows, "av" on POSIX); anything else records the pure-Python `#!python` shim
    (arcname "av", no extension -- on Windows specifically this means the fallback isn't
    directly invokable by name without a real `.exe` wrapper, a narrow, documented,
    unreached-on-a-published-wheel trade-off; POSIX needs no such wrapper for a shebang
    script).

    Best-effort and NEVER fatal to the overall build -- `aether_core` (the extension every
    test in this repo depends on) must always build even if the launcher's own compiler
    toolchain probe fails for some reason -- UNLESS `AV_REQUIRE_LAUNCHER=1` is set (release
    builds, and any CI job whose whole point is proving the native exe actually compiles):
    then a build failure re-raises instead of silently falling back, so it fails loudly with
    the real compiler diagnostic instead of shipping (or, worse in CI, quietly testing) a
    shim nobody asked for. Never set for an ordinary dev `pip install -e .` -- a broken/
    missing toolchain there must still leave a working `av-py`.
    """

    def run(self):
        super().run()
        try:
            self._build_launcher()
        except Exception as exc:  # pragma: no cover - best-effort, see class docstring
            if os.environ.get("AV_REQUIRE_LAUNCHER", "").strip().lower() in ("1", "true", "yes"):
                raise
            print(f"warning: native av launcher build failed, av will be the pure-Python "
                  f"shim: {exc}", file=sys.stderr)
            self._record_shim_artifact()

    def _build_launcher(self):
        version = self.distribution.get_version()
        launcher_build_dir = Path(self.build_temp) / "launcher"
        launcher_build_dir.mkdir(parents=True, exist_ok=True)

        # Overwrite the committed placeholder with the real version -- see that file's own
        # comment for why this is a generated header instead of a `-D` command-line macro.
        version_header = Path("src/launcher/av_launcher_version.h")
        version_header.write_text(
            '#pragma once\n#define AV_LAUNCHER_VERSION "' + version + '"\n', encoding="utf-8",
        )

        sources = [
            "src/launcher/av_launcher.cpp",
            "src/sha256.cpp", "src/sha256_backend.cpp",
            "src/sha256_shani.cpp", "src/sha256_arm.cpp",
        ]
        compiler = self.compiler
        exe_name = "av.exe" if _IS_MSVC else "av"
        link_libraries = ["kernel32", "user32", "advapi32"] if _IS_MSVC else []
        # -static-lib{stdc++,gcc} on Linux: this exe ships standalone (not next to a matching
        # libstdc++ the way aether_core.so, loaded BY that exact Python, can rely on one
        # being importable) -- statically linking the C++ runtime means it runs on a
        # manylinux-class distro whose system libstdc++ may be older than the one the
        # build compiler shipped. Not applied on macOS (its clang has no matching flag,
        # and Apple's system libc++ is always present and ABI-stable) or Windows (the
        # equivalent MSVC concern is CI pinning the same runtime the wheel targets).
        compile_args = (
            ["/O1", "/EHsc", "/std:c++17", "/DNOMINMAX"] if _IS_MSVC
            else ["-O2", "-std=c++17"]
        )
        link_args = (
            [] if _IS_MSVC
            else (["-static-libstdc++", "-static-libgcc"] if sys.platform.startswith("linux") else [])
        )

        objects = compiler.compile(
            sources,
            output_dir=str(launcher_build_dir),
            include_dirs=["src/", "src/launcher"],
            extra_postargs=compile_args,
        )
        compiler.link_executable(
            objects, "av", output_dir=str(launcher_build_dir),
            libraries=link_libraries, extra_postargs=link_args,
        )
        built_exe = launcher_build_dir / exe_name
        if not built_exe.exists():
            raise RuntimeError(f"link_executable reported success but {built_exe} is missing")
        if not _IS_MSVC:
            built_exe.chmod(0o755)

        self.distribution.av_launcher_artifact = (exe_name, str(built_exe), True)
        print(f"native av launcher: built ({built_exe}) -- will be injected into the wheel "
              f"as the real `av` command", file=sys.stderr)
        self._copy_to_interpreter_scripts_dir(built_exe, exe_name, is_binary=True)

    def _copy_to_interpreter_scripts_dir(self, artifact_path: Path, exe_name: str, is_binary: bool) -> None:
        # Copies whatever `av` should be for THIS build (the real compiled exe, or the
        # fallback shim/precompiled-shim if that's what happened instead) to this
        # interpreter's own Scripts/bin dir -- as `av-native[.exe]` (a directly-testable,
        # stable-path artifact for tests/test_launcher_native.py, AV_TEST_LAUNCHER /
        # shutil.which("av-native")) AND, since `av` is no longer any kind of entry point
        # (see pyproject.toml's comment on `av-py`), also directly as `av[.exe]` itself.
        # `WheelWithNativeLauncher` below does the equivalent for a REAL (non-editable)
        # install by injecting into the wheel -- but `pip install -e .` never runs
        # `bdist_wheel` at all, so without this copy an editable/dev install would have
        # av-py and av-native but no `av` whatsoever. This must run on EVERY path that
        # decides what `av` is (the successful build above, AND the shim fallback below) --
        # a real bug shipped once during this feature's own development where only the
        # successful-build path called this, so a build that fell back to the shim left a
        # STALE `av.exe` from some earlier successful build sitting untouched in Scripts,
        # silently masking the fact that a fresh install with a broken toolchain would have
        # had no working `av` at all (found by deliberately breaking the build to test the
        # fallback for real, not by reasoning about it in the abstract).
        candidate_dirs = [Path(sysconfig.get_path("scripts"))]
        try:
            candidate_dirs.append(Path(sysconfig.get_path("scripts", scheme="nt_user" if _IS_MSVC else "posix_user")))
        except (KeyError, ValueError):
            pass
        av_native_name = "av-native.exe" if _IS_MSVC else "av-native"
        last_exc = None
        for scripts_dir in candidate_dirs:
            try:
                scripts_dir.mkdir(parents=True, exist_ok=True)
                dest_native = scripts_dir / av_native_name
                dest_av = scripts_dir / exe_name
                if is_binary:
                    shutil.copy2(artifact_path, dest_native)
                    shutil.copy2(artifact_path, dest_av)
                else:
                    # The shim's `#!python` first line is a placeholder a real wheel
                    # install rewrites via pip's own `fix_script()` (see `_PY_SHIM`'s
                    # comment) -- a raw `shutil.copy2` here never goes through that, so an
                    # editable install whose native build fell back to this shim left a
                    # `#!python` literal on disk. The kernel's shebang parser takes that as
                    # a path relative to cwd, not a PATH lookup -- when run from a checkout
                    # that happens to contain a `python/` directory (this one does), exec
                    # hits that directory and fails with "bad interpreter: Permission
                    # denied" instead of running at all (found live: `launcher-native-posix`
                    # CI, both POSIX runners, whenever the native compile doesn't succeed).
                    # Rewriting to the real interpreter path here matches what pip would
                    # have done, so the shim is actually invokable the same way `av-py` is.
                    self._write_shim(artifact_path, dest_native)
                    self._write_shim(artifact_path, dest_av)
                if not _IS_MSVC:
                    # Executable bit -- needed regardless of `is_binary`: a POSIX shebang
                    # text script must be +x to be directly invokable exactly like a real
                    # binary would be.
                    dest_native.chmod(0o755)
                    dest_av.chmod(0o755)
                print(f"native av launcher: also copied to {scripts_dir} as {av_native_name} "
                      f"and {exe_name} (editable/direct-install convenience)", file=sys.stderr)
                return
            except OSError as exc:
                last_exc = exc
        print(f"native av launcher: could not copy to any interpreter scripts dir "
              f"({last_exc}) -- av-native/av unavailable this build", file=sys.stderr)

    @staticmethod
    def _write_shim(src: Path, dest: Path) -> None:
        """Copies the `#!python` text shim, rewriting that first line to this build's real
        interpreter path -- see the call site's comment for why a plain `shutil.copy2`
        leaves it non-invokable outside a real wheel install."""
        text = src.read_text(encoding="utf-8")
        first, _, rest = text.partition("\n")
        if first.strip() == "#!python":
            text = f"#!{sys.executable}\n{rest}"
        dest.write_text(text, encoding="utf-8", newline="\n")

    def _record_shim_artifact(self):
        # Windows specifically: a bare `.py` text file named `av` (no `.exe`) is not
        # directly invokable by name from cmd/PowerShell at all -- there's no shebang
        # mechanism to fall back on the way POSIX has one. `av_launcher_shim.cpp` is a
        # separate, minimal, PRECOMPILED (checked into git, never built here) fallback exe
        # for exactly this scenario -- see that file's own header comment for why it can't
        # just be compiled on demand (if the toolchain that would compile it is the thing
        # that's broken, nothing gets compiled, full stop). Used only when the REAL
        # launcher's own build just failed on Windows; anywhere else (a working Windows
        # build, or any POSIX platform) never touches this at all.
        precompiled = Path("src/launcher/precompiled/av_shim_win32.exe")
        if _IS_MSVC and precompiled.exists():
            self.distribution.av_launcher_artifact = ("av.exe", str(precompiled), True)
            print(f"native av launcher: using precompiled fallback shim ({precompiled}) "
                  f"as the real `av` command", file=sys.stderr)
            self._copy_to_interpreter_scripts_dir(precompiled, "av.exe", is_binary=True)
            return
        shim_path = Path(self.build_temp) / "launcher" / "av_shim.py"
        shim_path.parent.mkdir(parents=True, exist_ok=True)
        shim_path.write_text(_PY_SHIM, encoding="utf-8", newline="\n")
        self.distribution.av_launcher_artifact = ("av", str(shim_path), False)
        # POSIX only reaches here in practice (Windows always has the precompiled shim
        # above, as long as it's present) -- `_copy_to_interpreter_scripts_dir` already
        # chmods +x unconditionally on non-Windows, which is exactly what a shebang text
        # script needs to be directly invokable, same as a real binary.
        self._copy_to_interpreter_scripts_dir(shim_path, "av", is_binary=False)


class WheelWithNativeLauncher(_bdist_wheel or object):
    """Injects whatever `BuildExtWithLauncher` recorded as `av` directly into the already-
    built wheel's `.data/scripts/` directory -- see that class's docstring and the module
    comment above `_PY_SHIM` for why this bypasses `scripts=`/`build_scripts` entirely.

    `av` must NEVER also be a `[project.scripts]` entry point (see pyproject.toml's own
    comment on `av-py`): verified by reading pip's installer directly
    (`pip._internal.operations.install.wheel.is_entrypoint_wrapper`) -- a `.data/scripts/`
    file is silently DROPPED at install time whenever its name (minus `.exe`) matches a
    registered console/gui script name, on the assumption it's a leftover setuptools-
    generated wrapper. Since nothing here registers `av` as an entry point, that filter
    never triggers and this file installs verbatim.
    """

    def run(self):
        super().run()
        try:
            self._inject_av_script()
        except Exception as exc:  # pragma: no cover - best-effort, never fail the build over this
            print(f"warning: could not inject native av launcher into wheel: {exc}",
                  file=sys.stderr)

    def _inject_av_script(self):
        artifact = getattr(self.distribution, "av_launcher_artifact", None)
        if artifact is None:
            print("native av launcher: no artifact recorded (build_ext didn't run?) -- "
                  "wheel will have no `av` command at all", file=sys.stderr)
            return
        arcname_base, src_path, is_binary = artifact

        wheel_path = self._find_built_wheel()
        if wheel_path is None:
            print("native av launcher: could not locate the built wheel to inject into",
                  file=sys.stderr)
            return

        with open(src_path, "rb") as f:
            payload = f.read()

        self._rewrite_wheel_with_extra_script(wheel_path, arcname_base, payload, is_binary)

    def _find_built_wheel(self):
        dist_dir = Path(self.dist_dir)
        candidates = sorted(dist_dir.glob("*.whl"), key=lambda p: p.stat().st_mtime, reverse=True)
        return candidates[0] if candidates else None

    @staticmethod
    def _record_row(name: str, data: bytes) -> list[str]:
        digest = hashlib.sha256(data).digest()
        b64 = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
        return [name, f"sha256={b64}", str(len(data))]

    def _rewrite_wheel_with_extra_script(self, wheel_path: Path, arcname_base: str,
                                          payload: bytes, is_binary: bool) -> None:
        tmp_path = wheel_path.with_suffix(".whl.tmp")
        with zipfile.ZipFile(wheel_path, "r") as src:
            record_path = next(
                (n for n in src.namelist() if n.endswith(".dist-info/RECORD")), None,
            )
            if record_path is None:
                raise RuntimeError("built wheel has no RECORD file")
            # namever ("<distribution>-<version>", exactly as setuptools normalized it for
            # THIS wheel) read straight off the real .dist-info path inside the wheel --
            # never re-derived from the wheel FILENAME, whose distribution/version fields
            # use a different, stricter normalization (runs of `-_.` collapsed to `_`) that
            # would silently produce the wrong `.data` directory name if guessed instead.
            namever = record_path.rsplit(".dist-info/RECORD", 1)[0]
            data_arcname = f"{namever}.data/scripts/{arcname_base}"

            entries = [
                (name, src.read(name), src.getinfo(name))
                for name in src.namelist()
                if name != record_path and not src.getinfo(name).is_dir()
            ]
            fallback_date = entries[0][2].date_time if entries else (2020, 1, 1, 0, 0, 0)

        with zipfile.ZipFile(tmp_path, "w", zipfile.ZIP_DEFLATED) as dst:
            record_rows = []
            for name, data, info in entries:
                dst.writestr(info, data)
                record_rows.append(self._record_row(name, data))

            new_info = zipfile.ZipInfo(data_arcname, date_time=fallback_date)
            new_info.compress_type = zipfile.ZIP_DEFLATED
            # Real bug (found live via `smoke-wheel-linux`'s "Permission denied", not a
            # shebang problem): pip's `zip_item_is_executable()` requires the upper 16 bits
            # of `external_attr` to be a full Unix `st_mode` -- `stat.S_ISREG(mode)` on just
            # `0o755` is False (no S_IFREG file-type bits set at all), so pip's installer
            # silently skipped the post-extract chmod +x and every installed wheel's `av`
            # came out non-executable. Must OR in `stat.S_IFREG`, not just the permission bits.
            new_info.external_attr = (stat.S_IFREG | 0o755) << 16
            dst.writestr(new_info, payload)
            record_rows.append(self._record_row(data_arcname, payload))

            record_rows.append([record_path, "", ""])
            buf = io.StringIO()
            writer = csv.writer(buf, delimiter=",", quotechar='"', lineterminator="\n")
            writer.writerows(record_rows)
            dst.writestr(record_path, buf.getvalue())

        tmp_path.replace(wheel_path)
        print(f"native av launcher: injected as {data_arcname} in {wheel_path.name}",
              file=sys.stderr)


_cmdclass = {"build_ext": BuildExtWithLauncher}
if _bdist_wheel is not None:
    _cmdclass["bdist_wheel"] = WheelWithNativeLauncher
else:
    print("warning: no bdist_wheel command available (setuptools < 70.1 and no `wheel` "
          "package) -- native av launcher will NOT be injected into any built wheel this "
          "run; av-py remains available regardless", file=sys.stderr)


setup(
    ext_modules=ext_modules,
    cmdclass=_cmdclass,
    # v1.3.0 fix (Probleme.md): "av_server.migrations.versions" MUST be listed explicitly.
    # setuptools' build_py (the command that decides what .py files land in a WHEEL) only
    # descends into a package's OWN directory for each name in this list — it does not
    # recurse into an undeclared subdirectory just because the parent package is listed,
    # regardless of include-package-data/setuptools-scm (those affect the SDIST's MANIFEST,
    # a completely different mechanism, which is why `python -m build --sdist` correctly
    # included every migrations/versions/*.py file while `pip wheel .` silently dropped
    # them all — proven live: a wheel built before this fix had 0001-0004 but never 0005,
    # even after `git add`ing it). alembic's own versions/ directories don't need
    # __init__.py (ScriptDirectory finds .py files via its own walk, not Python imports),
    # so this line existing is the ONLY thing that makes them real, wheel-visible packages.
    packages=["av_cli", "av_server", "av_server.migrations", "av_server.migrations.versions",
              "av_plugins", "av_sdk"],
    package_dir={"": "python"},
    package_data={
        "av_server.migrations": ["script.py.mako"],
        # .avh v2 contract artifact: shipped so external validators (jsonschema CLI,
        # editors, other languages) can validate handoff documents against the exact
        # schema the project enforces structurally via handoff.validate_handoff().
        "av_cli": ["schemas/*.schema.json"],
    },
)
