"""v1.3.0 (todo.md item 22): scripts/append_perf_history.py — the pure rendering/merge
logic (never the real speedcheck capture itself, which is exercised manually/by CI; see
the script's own module docstring for why it's a maintainer-run-locally tool, never CI).
"""
import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT_PATH = Path(__file__).resolve().parents[1] / "scripts" / "append_perf_history.py"
_spec = importlib.util.spec_from_file_location("append_perf_history", _SCRIPT_PATH)
aph = importlib.util.module_from_spec(_spec)
sys.modules["append_perf_history"] = aph
_spec.loader.exec_module(aph)


def _entry(date="2026-09-01", version="1.3.0", **probes):
    return {"date": date, "version": version, "os": "Linux", "python": "3.12.0", "probes": probes}


def test_probe_value_matches_by_prefix_not_exact_equality():
    probes = {"Index.save() (500 entries)": 12.3}
    assert aph._probe_value(probes, "Index.save()") == 12.3
    assert aph._probe_value(probes, "Index.load()") is None


def test_render_trend_table_with_no_entries():
    out = aph.render_trend_table({"schema": "perf-history-1.0", "entries": []})
    assert aph.TREND_START in out and aph.TREND_END in out
    assert "No captures yet" in out


def test_render_trend_table_renders_a_row_per_entry():
    history = {
        "schema": "perf-history-1.0",
        "entries": [
            _entry(date="2026-08-01", version="1.2.5", **{"Index.save() (500 entries)": 10.0}),
            _entry(date="2026-09-01", version="1.3.0", **{"Index.save() (500 entries)": 20.0}),
        ],
    }
    out = aph.render_trend_table(history)
    assert "2026-08-01" in out and "1.2.5" in out and "10.0 ms" in out
    assert "2026-09-01" in out and "1.3.0" in out and "20.0 ms" in out
    # A tracked column with no matching probe in this entry renders as an em dash, not KeyError.
    assert "—" in out


def test_render_trend_table_keeps_only_the_most_recent_ten():
    entries = [_entry(date=f"2026-01-{i:02d}") for i in range(1, 16)]
    out = aph.render_trend_table({"schema": "perf-history-1.0", "entries": entries})
    assert "2026-01-15" in out  # most recent
    assert "2026-01-06" in out  # 10th most recent (15 - 10 + 1)
    assert "2026-01-05" not in out  # older than the 10-entry window
    assert "showing the most recent 10" in out


def test_update_benchmarks_md_appends_the_block_when_no_markers_exist(tmp_path, monkeypatch):
    bench = tmp_path / "BENCHMARKS.md"
    bench.write_text("# Aether-Vault Benchmarks\n\nSome existing content.\n", encoding="utf-8")
    monkeypatch.setattr(aph, "BENCHMARKS_PATH", bench)

    history = {"schema": "perf-history-1.0", "entries": [_entry()]}
    rendered = aph.update_benchmarks_md(history)
    assert "Some existing content." in rendered
    assert aph.TREND_START in rendered and aph.TREND_END in rendered


def test_update_benchmarks_md_replaces_only_the_marked_block_on_a_second_run(tmp_path, monkeypatch):
    bench = tmp_path / "BENCHMARKS.md"
    monkeypatch.setattr(aph, "BENCHMARKS_PATH", bench)

    history_v1 = {"schema": "perf-history-1.0", "entries": [_entry(version="1.3.0")]}
    bench.write_text(
        "# Header\n\nUnrelated content that must survive.\n\n"
        + aph.update_benchmarks_md(history_v1).split("Unrelated content that must survive.\n\n", 1)[-1],
        encoding="utf-8",
    )
    # Simulate `av benchmark --markdown` NOT having run again — re-running with a second
    # entry should replace ONLY the marked block, leaving the rest of the file untouched.
    history_v2 = {
        "schema": "perf-history-1.0",
        "entries": [_entry(version="1.3.0"), _entry(date="2026-09-02", version="1.3.1")],
    }
    rendered = aph.update_benchmarks_md(history_v2)
    assert rendered.count(aph.TREND_START) == 1
    assert "Unrelated content that must survive." in rendered
    assert "1.3.1" in rendered
    assert "2026-09-02" in rendered


def test_load_history_returns_an_empty_skeleton_when_the_file_is_missing(tmp_path, monkeypatch):
    monkeypatch.setattr(aph, "PERF_HISTORY_PATH", tmp_path / "does-not-exist.json")
    history = aph.load_history()
    assert history == {"schema": "perf-history-1.0", "entries": []}


def test_project_version_prefers_the_live_generated_version_file(monkeypatch):
    # A dev machine with multiple registered distributions can make importlib.metadata
    # resolve non-deterministically, so av_cli/_version.py (regenerated by setuptools-scm
    # on every build) must win, matching ui._get_version()'s identical ordering.
    import av_cli._version as v

    monkeypatch.setattr(v, "__version__", "9.9.9-live-test", raising=False)
    monkeypatch.setattr("importlib.metadata.version", lambda name: "1.0.0-stale-metadata")
    assert aph._project_version() == "9.9.9-live-test"


def test_project_version_falls_back_to_installed_metadata_without_the_version_file(monkeypatch):
    import av_cli._version as v

    monkeypatch.delattr(v, "__version__", raising=False)
    monkeypatch.setattr("importlib.metadata.version", lambda name: "5.5.5-metadata-test")
    assert aph._project_version() == "5.5.5-metadata-test"


def test_project_version_never_raises_even_with_nothing_installed(monkeypatch):
    # Best-effort: the version file, importlib.metadata, and setuptools_scm may all fail
    # -- must degrade to a literal "unknown" string, never raise.
    import importlib.metadata as im
    import av_cli._version as v

    monkeypatch.delattr(v, "__version__", raising=False)

    def _boom(*a, **k):
        raise im.PackageNotFoundError

    monkeypatch.setattr(im, "version", _boom)
    result = aph._project_version()
    assert isinstance(result, str) and result
