// V1.6.0 native `av` launcher -- Windows AND POSIX (Linux/macOS).
//
// A small executable that speaks the daemon's real wire protocol (daemon_protocol.py,
// PROTOCOL_VERSION 1 -- a single request frame, a single response frame, no streaming, no
// cancel-over-wire) directly, without ever starting a Python interpreter, for an
// allowlisted command against a warm daemon. Falls back transparently to the real Python
// CLI for `--help`, non-allowlisted commands, no repo, no reachable daemon, or a rejected/
// forged token -- every fallback re-execs the *original, unmodified* argv, so correctness
// never depends on this binary existing at all.
//
// Scope/verification note: every Windows code path here is built AND exercised end-to-end
// on this project's own dev box against a live `av daemon`
// (tests/test_launcher_native.py, `.github/workflows/tests.yml`'s `launcher-native-windows`
// job). The POSIX branches below were written to the SAME protocol/design and reviewed with
// the same care, but this project's only dev box has no Linux/macOS toolchain to compile OR
// execute them locally -- `.github/workflows/tests.yml`'s `launcher-native-posix` job (a
// matrix over ubuntu-latest and macos-latest) is what actually builds and runs
// `tests/test_launcher_native.py` against these paths for real, since a real CI runner can
// do what this box cannot. That is a genuine difference in HOW correctness was established
// here versus the Windows side, not a lower bar for shipping it -- see
// src/launcher/README.md for the full account.
#if !defined(_WIN32) && !defined(__unix__) && !defined(__APPLE__)
#error "av_launcher.cpp supports Windows and POSIX (Linux/macOS) only"
#endif

#ifdef _WIN32
#define _CRT_RAND_S  // must precede <stdlib.h> -- enables the CSPRNG rand_s() variant
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <io.h>
#else
#include <cerrno>
#include <cstdio>
#include <fcntl.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#if defined(__APPLE__)
#include <mach-o/dyld.h>
#endif
#endif

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <optional>
#include <string>
#include <vector>

#ifdef _WIN32
#include <cwctype>
#endif

#include "json.hpp"
#include "sha256.h"
// Generated (or, for a bare manual build, the committed placeholder) -- `#define
// AV_LAUNCHER_VERSION "<setuptools-scm version>"`. A `-D` command-line macro would need the
// literal string-quote characters to survive the shell/compiler's own de-escaping, which is
// exactly the kind of fragile cross-shell quoting this project avoids elsewhere; a real
// header generated by setup.py's `_build_launcher()` sidesteps it entirely.
#include "av_launcher_version.h"

namespace fs = std::filesystem;
using json = nlohmann::json;

namespace {

// -- global options mirrored from launcher.py's _GLOBAL_FLAGS / _GLOBAL_VALUE_OPTS ---------
// Keep these two lists in lockstep with python/av_cli/launcher.py -- both independently
// implement click's own global-option parsing so neither has to import click.
const std::vector<std::string> kGlobalFlags = {"--verbose", "--silent", "--version"};
const std::vector<std::string> kGlobalValueOpts = {"--output"};

// Mirrors python/av_cli/daemon_common.py::ALLOWED_COMMANDS. Deliberately duplicated rather
// than read from anywhere at runtime -- this binary is only ever trusted to match the
// Python side because AV_LAUNCHER_VERSION is baked in at the same build and the daemon
// independently rejects any cli_version it doesn't recognize (handle_request's
// "version_skew"), so a stale launcher binary talking to a newer daemon fails closed, not
// open, even if this list itself ever drifts.
const std::vector<std::string> kAllowedCommands = {
    "add", "status", "commit", "push", "fetch", "unstage", "log", "diff", "context", "run",
};

// ============================================================================
// Platform-neutral helpers: everything below this point that ISN'T inside an
// `#ifdef _WIN32` operates purely on std::string/std::filesystem::path, with wide-string
// conversion (Windows) or direct byte passthrough (POSIX, already UTF-8 from the OS)
// happening only at the few OS API call sites that need it. This is deliberate: the actual
// protocol/business logic in run() at the bottom exists ONCE, not as two parallel
// implementations that could silently drift -- the same "one implementation" discipline
// this project applies to e.g. CdcCutter (src/core.cpp).
// ============================================================================

#ifdef _WIN32
std::string wide_to_utf8(const std::wstring &w) {
    if (w.empty()) return {};
    int size = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), nullptr, 0, nullptr, nullptr);
    std::string out(size, '\0');
    WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), out.data(), size, nullptr, nullptr);
    return out;
}

std::wstring utf8_to_wide(const std::string &s) {
    if (s.empty()) return {};
    int size = MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
    std::wstring out(size, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), out.data(), size);
    return out;
}
#endif

// -- env access: one std::string-based surface for both platforms --------------------------

std::optional<std::string> get_env(const char *name) {
#ifdef _WIN32
    std::wstring wname = utf8_to_wide(name);
    DWORD needed = GetEnvironmentVariableW(wname.c_str(), nullptr, 0);
    if (needed == 0) return std::nullopt;
    std::wstring buf(needed, L'\0');
    DWORD written = GetEnvironmentVariableW(wname.c_str(), buf.data(), needed);
    if (written == 0) return std::nullopt;
    buf.resize(written);
    return wide_to_utf8(buf);
#else
    const char *v = std::getenv(name);
    if (!v) return std::nullopt;
    return std::string(v);
#endif
}

void set_env(const char *name, const std::string &value) {
#ifdef _WIN32
    SetEnvironmentVariableW(utf8_to_wide(name).c_str(), utf8_to_wide(value).c_str());
#else
    setenv(name, value.c_str(), 1);
#endif
}

bool truthy_env(const char *name) {
    auto v = get_env(name);
    if (!v) return false;
    std::string s = *v;
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return std::tolower(c); });
    return s == "1" || s == "true" || s == "yes";
}

void trace(const std::string &msg) {
    if (truthy_env("AV_LAUNCHER_TRACE")) {
        std::cerr << "[av-native] " << msg << "\n";
    }
}

// -- argv classification (mirrors launcher.py::_first_subcommand) --------------------------

std::optional<std::string> first_subcommand(const std::vector<std::string> &argv) {
    size_t i = 0;
    while (i < argv.size()) {
        const std::string &tok = argv[i];
        if (std::find(kGlobalFlags.begin(), kGlobalFlags.end(), tok) != kGlobalFlags.end()) {
            i += 1;
            continue;
        }
        if (std::find(kGlobalValueOpts.begin(), kGlobalValueOpts.end(), tok) != kGlobalValueOpts.end()) {
            i += 2;
            continue;
        }
        bool matched_value_form = false;
        for (const auto &opt : kGlobalValueOpts) {
            if (tok.rfind(opt + "=", 0) == 0) {
                matched_value_form = true;
                break;
            }
        }
        if (matched_value_form) {
            i += 1;
            continue;
        }
        return tok;
    }
    return std::nullopt;
}

bool is_allowed(const std::string &cmd) {
    return std::find(kAllowedCommands.begin(), kAllowedCommands.end(), cmd) != kAllowedCommands.end();
}

// -- repo root discovery (mirrors launcher.py::_repo_root_or_none) -------------------------

std::optional<fs::path> find_repo_root() {
    std::error_code ec;
    fs::path cwd = fs::current_path(ec);
    if (ec) return std::nullopt;
    fs::path dir = cwd;
    while (true) {
        std::error_code ec2;
        if (fs::is_directory(dir / ".av", ec2)) return fs::weakly_canonical(dir, ec2);
        if (!dir.has_parent_path() || dir.parent_path() == dir) return std::nullopt;
        dir = dir.parent_path();
    }
}

fs::path own_exe_path() {
#ifdef _WIN32
    std::vector<wchar_t> buf(MAX_PATH);
    for (;;) {
        DWORD n = GetModuleFileNameW(nullptr, buf.data(), (DWORD)buf.size());
        if (n == 0) return {};
        if (n < buf.size() - 1) {
            std::error_code ec;
            return fs::weakly_canonical(fs::path(buf.data(), buf.data() + n), ec);
        }
        buf.resize(buf.size() * 2);
    }
#elif defined(__APPLE__)
    uint32_t size = 0;
    _NSGetExecutablePath(nullptr, &size);  // first call always fails, just to learn `size`
    std::vector<char> buf(size);
    if (_NSGetExecutablePath(buf.data(), &size) != 0) return {};
    std::error_code ec;
    return fs::weakly_canonical(fs::path(buf.data()), ec);
#else
    std::error_code ec;
    fs::path p = fs::read_symlink("/proc/self/exe", ec);
    if (ec) return {};
    return fs::weakly_canonical(p, ec);
#endif
}

// -- runtime dir / discovery file (mirrors daemon_common.py) --------------------------------

fs::path home_dir() {
#ifdef _WIN32
    if (auto up = get_env("USERPROFILE")) return fs::u8path(*up);
    auto drive = get_env("HOMEDRIVE");
    auto path = get_env("HOMEPATH");
    if (drive && path) return fs::u8path(*drive + *path);
    if (auto home = get_env("HOME")) return fs::u8path(*home);
    return fs::current_path();
#else
    if (auto home = get_env("HOME")) return fs::u8path(*home);
    return fs::current_path();
#endif
}

fs::path user_runtime_dir() {
    if (auto xdg = get_env("XDG_RUNTIME_DIR")) return fs::u8path(*xdg) / "aether-vault";
    return home_dir() / ".aether-vault" / "run";
}

std::string sha256_hex(const std::string &s) {
    return SHA256::hash_bytes(s);
}

// Keyed by the EXACT strings this process computes for its own exe path and repo root --
// daemon_common.launcher_discovery_file() on the Python side hashes the identical two
// strings verbatim (received via AV_LAUNCHER_EXE/AV_LAUNCHER_REPO env vars during a
// fallback exec), so neither side has to agree on path-normalization rules, only on not
// re-normalizing what the other already decided.
fs::path discovery_file(const std::string &exe_s, const std::string &repo_s) {
    std::string key = sha256_hex(exe_s + "|" + repo_s).substr(0, 16);
    return user_runtime_dir() / ("launcher-" + key + ".json");
}

std::string hmac_sha256_hex(const std::string &key, const std::string &msg) {
    constexpr size_t kBlock = 64;
    std::vector<uint8_t> key_block(kBlock, 0);
    if (key.size() > kBlock) {
        SHA256 h;
        h.update(reinterpret_cast<const uint8_t *>(key.data()), key.size());
        uint8_t *d = h.digest();
        std::copy(d, d + 32, key_block.begin());
    } else {
        std::copy(key.begin(), key.end(), key_block.begin());
    }
    std::vector<uint8_t> ipad(kBlock), opad(kBlock);
    for (size_t i = 0; i < kBlock; ++i) {
        ipad[i] = key_block[i] ^ 0x36;
        opad[i] = key_block[i] ^ 0x5c;
    }
    SHA256 inner;
    inner.update(ipad.data(), ipad.size());
    inner.update(reinterpret_cast<const uint8_t *>(msg.data()), msg.size());
    uint8_t inner_digest[32];
    std::memcpy(inner_digest, inner.digest(), 32);

    SHA256 outer;
    outer.update(opad.data(), opad.size());
    outer.update(inner_digest, 32);
    return outer.hexdigest();
}

std::string random_hex(size_t nbytes) {
    std::string out;
    out.reserve(nbytes * 2);
    static const char *hexchars = "0123456789abcdef";
#ifdef _WIN32
    size_t produced = 0;
    while (produced < nbytes) {
        unsigned int r = 0;
        if (rand_s(&r) != 0) r = (unsigned int)GetTickCount64() ^ (unsigned int)produced;
        for (int b = 0; b < 4 && produced < nbytes; ++b, ++produced) {
            uint8_t byte = (uint8_t)((r >> (b * 8)) & 0xFF);
            out.push_back(hexchars[byte >> 4]);
            out.push_back(hexchars[byte & 0x0F]);
        }
    }
#else
    // /dev/urandom rather than a Linux-only getrandom()/BSD-only arc4random_buf() --
    // present and non-blocking-after-boot on every Linux and macOS this project targets.
    std::vector<uint8_t> bytes(nbytes);
    bool ok = false;
    {
        std::ifstream f("/dev/urandom", std::ios::binary);
        if (f) {
            f.read(reinterpret_cast<char *>(bytes.data()), (std::streamsize)nbytes);
            ok = f.gcount() == (std::streamsize)nbytes;
        }
    }
    if (!ok) {
        // /dev/urandom is unavailable in some minimal/sandboxed containers -- a nonce only
        // needs to be non-repeating for HMAC replay-safety within one process's requests,
        // never a secret itself, so a time+pid-seeded fallback is an acceptable last resort
        // (the token itself, the actual secret, is always read from the 0600 key file).
        uint64_t seed = (uint64_t)std::chrono::steady_clock::now().time_since_epoch().count() ^
                        (uint64_t)getpid();
        for (size_t i = 0; i < nbytes; ++i) {
            seed = seed * 6364136223846793005ULL + 1442695040888963407ULL;
            bytes[i] = (uint8_t)(seed >> 33);
        }
    }
    for (uint8_t byte : bytes) {
        out.push_back(hexchars[byte >> 4]);
        out.push_back(hexchars[byte & 0x0F]);
    }
#endif
    return out;
}

// -- transport: named pipe (Windows) / AF_UNIX socket (POSIX) -------------------------------
// Both sides implement the identical daemon_protocol.py framing (4-byte big-endian length +
// UTF-8 JSON) over whatever byte stream the platform gives us -- Conn below is the one
// pair of send_frame/recv_frame free functions every platform's connection type overloads.

#ifdef _WIN32
struct Conn {
    HANDLE h = INVALID_HANDLE_VALUE;

    Conn() = default;
    // Move-only, and NOT the compiler-generated kind: a class with a user-declared
    // destructor gets no implicit move constructor at all (C++11 rule) -- a real bug this
    // exact struct shipped once during this feature's own development (see git history /
    // Probleme.md): the by-value return from a connect helper silently fell back to the
    // implicit COPY constructor (a plain memberwise copy of the raw handle), and the
    // temporary's destructor then closed that same handle out from under the caller.
    Conn(const Conn &) = delete;
    Conn &operator=(const Conn &) = delete;
    Conn(Conn &&other) noexcept : h(other.h) { other.h = INVALID_HANDLE_VALUE; }
    Conn &operator=(Conn &&other) noexcept {
        if (this != &other) {
            if (h != INVALID_HANDLE_VALUE) CloseHandle(h);
            h = other.h;
            other.h = INVALID_HANDLE_VALUE;
        }
        return *this;
    }
    ~Conn() {
        if (h != INVALID_HANDLE_VALUE) CloseHandle(h);
    }
    bool valid() const { return h != INVALID_HANDLE_VALUE; }
};

std::optional<Conn> connect_daemon(const std::string &endpoint) {
    std::wstring wname = utf8_to_wide(endpoint);
    for (int attempt = 0; attempt < 2; ++attempt) {
        HANDLE h = CreateFileW(wname.c_str(), GENERIC_READ | GENERIC_WRITE, 0, nullptr,
                                OPEN_EXISTING, 0, nullptr);
        if (h != INVALID_HANDLE_VALUE) {
            Conn c;
            c.h = h;
            return c;
        }
        DWORD err = GetLastError();
        trace("CreateFileW attempt " + std::to_string(attempt) + " failed, GetLastError=" +
              std::to_string(err));
        if (err == ERROR_PIPE_BUSY && attempt == 0) {
            WaitNamedPipeW(wname.c_str(), 200);
            continue;
        }
        break;
    }
    return std::nullopt;
}

bool write_all(Conn &c, const uint8_t *data, size_t len) {
    size_t off = 0;
    while (off < len) {
        DWORD written = 0;
        if (!WriteFile(c.h, data + off, (DWORD)(len - off), &written, nullptr)) return false;
        if (written == 0) return false;
        off += written;
    }
    return true;
}

bool read_all(Conn &c, uint8_t *out, size_t len) {
    size_t off = 0;
    while (off < len) {
        DWORD got = 0;
        if (!ReadFile(c.h, out + off, (DWORD)(len - off), &got, nullptr)) return false;
        if (got == 0) return false;
        off += got;
    }
    return true;
}
#else
// Same move-only discipline as the Windows Conn above, for the same reason: a
// user-declared destructor suppresses the IMPLICIT move constructor too (not just the
// copy constructor), so without these explicit ones a by-value return from
// connect_daemon() below would silently fall back to a memberwise COPY of the raw fd --
// two Conn objects owning (and, on scope exit, both closing) the same socket. Written
// correctly from the start here specifically because the Windows sibling already paid for
// this exact bug once (see its own comment) -- this side has never been built or run on
// this project's Windows-only dev box, so getting it right by construction rather than by
// testing matters more here, not less.
struct Conn {
    int fd = -1;

    Conn() = default;
    Conn(const Conn &) = delete;
    Conn &operator=(const Conn &) = delete;
    Conn(Conn &&other) noexcept : fd(other.fd) { other.fd = -1; }
    Conn &operator=(Conn &&other) noexcept {
        if (this != &other) {
            if (fd >= 0) close(fd);
            fd = other.fd;
            other.fd = -1;
        }
        return *this;
    }
    ~Conn() {
        if (fd >= 0) close(fd);
    }
    bool valid() const { return fd >= 0; }
};

std::optional<Conn> connect_daemon(const std::string &endpoint) {
    int fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (fd < 0) {
        trace("socket() failed, errno=" + std::to_string(errno));
        return std::nullopt;
    }
    struct sockaddr_un addr {};
    addr.sun_family = AF_UNIX;
    if (endpoint.size() >= sizeof(addr.sun_path)) {
        trace("socket path too long for sockaddr_un: " + endpoint);
        close(fd);
        return std::nullopt;
    }
    std::memcpy(addr.sun_path, endpoint.c_str(), endpoint.size() + 1);

    // A short, bounded connect attempt (matching the Windows pipe-busy retry's own ~200ms
    // budget) via a non-blocking connect + poll, rather than trusting the OS's default
    // blocking-connect timeout (which for AF_UNIX is typically immediate success/failure
    // anyway, but a busy accept backlog on a slow/loaded box could still make this hang
    // without the timeout).
    int flags = fcntl(fd, F_GETFL, 0);
    fcntl(fd, F_SETFL, flags | O_NONBLOCK);
    int rc = connect(fd, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr));
    if (rc != 0 && errno != EINPROGRESS) {
        trace("connect() failed immediately, errno=" + std::to_string(errno));
        close(fd);
        return std::nullopt;
    }
    if (rc != 0) {
        struct pollfd pfd {};
        pfd.fd = fd;
        pfd.events = POLLOUT;
        int pr = poll(&pfd, 1, 200);
        if (pr <= 0) {
            trace("connect() timed out waiting for the daemon");
            close(fd);
            return std::nullopt;
        }
        int so_error = 0;
        socklen_t len = sizeof(so_error);
        getsockopt(fd, SOL_SOCKET, SO_ERROR, &so_error, &len);
        if (so_error != 0) {
            trace("connect() completed with error " + std::to_string(so_error));
            close(fd);
            return std::nullopt;
        }
    }
    fcntl(fd, F_SETFL, flags);  // back to blocking for the actual request/response I/O
    Conn c;
    c.fd = fd;
    return c;
}

// EINTR (a signal interrupted the blocking call before any bytes moved) is retried rather
// than treated as failure -- a real, POSIX-specific case Windows' WriteFile/ReadFile have
// no equivalent of, and one every long-lived blocking syscall on this platform is expected
// to handle. `n == 0` on write() would mean nothing was written despite no error (not
// actually possible for a stream socket short of len==0, kept as a defensive bail-out
// rather than spinning); on read() it's the real, common case -- the daemon closed its end
// of the socket, mid-frame or otherwise, and this maps that straight to the same "false =
// connection lost" contract the Windows ReadFile==0 branch already has.
bool write_all(Conn &c, const uint8_t *data, size_t len) {
    size_t off = 0;
    while (off < len) {
        ssize_t n = write(c.fd, data + off, len - off);
        if (n < 0) {
            if (errno == EINTR) continue;
            return false;
        }
        if (n == 0) return false;
        off += (size_t)n;
    }
    return true;
}

bool read_all(Conn &c, uint8_t *out, size_t len) {
    size_t off = 0;
    while (off < len) {
        ssize_t n = read(c.fd, out + off, len - off);
        if (n < 0) {
            if (errno == EINTR) continue;
            return false;
        }
        if (n == 0) return false;
        off += (size_t)n;
    }
    return true;
}
#endif

bool send_frame(Conn &c, const json &obj) {
    std::string payload = obj.dump();
    uint32_t len = (uint32_t)payload.size();
    uint8_t header[4] = {
        (uint8_t)((len >> 24) & 0xFF), (uint8_t)((len >> 16) & 0xFF),
        (uint8_t)((len >> 8) & 0xFF), (uint8_t)(len & 0xFF),
    };
    if (!write_all(c, header, 4)) return false;
    return write_all(c, reinterpret_cast<const uint8_t *>(payload.data()), payload.size());
}

std::optional<json> recv_frame(Conn &c) {
    uint8_t header[4];
    if (!read_all(c, header, 4)) return std::nullopt;
    uint32_t len = (uint32_t(header[0]) << 24) | (uint32_t(header[1]) << 16) |
                   (uint32_t(header[2]) << 8) | uint32_t(header[3]);
    constexpr uint32_t kMaxFrame = 8 * 1024 * 1024;
    if (len > kMaxFrame) return std::nullopt;
    std::string payload(len, '\0');
    if (len > 0 && !read_all(c, reinterpret_cast<uint8_t *>(payload.data()), len)) return std::nullopt;
    try {
        return json::parse(payload);
    } catch (const json::exception &) {
        return std::nullopt;
    }
}

// -- env allowlist (mirrors daemon_common.py::allowlisted_env) -----------------------------

#ifndef _WIN32
extern char **environ;
#endif

json collect_allowlisted_env() {
    json env_obj = json::object();
    static const std::vector<std::string> kExact = {"NO_COLOR", "FORCE_COLOR", "HOME",
                                                      "USERPROFILE", "COLUMNS"};
#ifdef _WIN32
    LPWCH block = GetEnvironmentStringsW();
    if (!block) return env_obj;
    for (LPWCH p = block; *p != L'\0';) {
        std::wstring entry(p);
        p += entry.size() + 1;
        size_t eq = entry.find(L'=');
        if (eq == std::wstring::npos || eq == 0) continue;  // skip "=C:=..." drive-cwd vars
        std::string key = wide_to_utf8(entry.substr(0, eq));
        std::string val = wide_to_utf8(entry.substr(eq + 1));
        bool keep = key.rfind("AV_", 0) == 0 || std::find(kExact.begin(), kExact.end(), key) != kExact.end();
        if (keep) env_obj[key] = val;
    }
    FreeEnvironmentStringsW(block);
#else
    for (char **p = environ; *p != nullptr; ++p) {
        std::string entry(*p);
        size_t eq = entry.find('=');
        if (eq == std::string::npos || eq == 0) continue;
        std::string key = entry.substr(0, eq);
        std::string val = entry.substr(eq + 1);
        bool keep = key.rfind("AV_", 0) == 0 || std::find(kExact.begin(), kExact.end(), key) != kExact.end();
        if (keep) env_obj[key] = val;
    }
#endif
    return env_obj;
}

// -- output --------------------------------------------------------------------------------

// The daemon's captured stdout/stderr (io.StringIO server-side) holds plain "\n" only --
// StringIO never applies newline translation. On WINDOWS, a client that ran the SAME
// command in-process instead prints through Python's real sys.stdout, a text-mode stream
// that translates "\n" -> "\r\n" on every write; this reproduces that explicitly so
// daemon-served output through the launcher matches the in-process path byte-for-byte on
// multi-line output. On POSIX, Python's own text-mode line ending IS "\n" -- there is
// nothing to translate, and doing so would corrupt the output instead of matching it.
std::string translate_newlines(const std::string &text) {
#ifdef _WIN32
    std::string out;
    out.reserve(text.size());
    for (size_t i = 0; i < text.size(); ++i) {
        if (text[i] == '\n' && (i == 0 || text[i - 1] != '\r')) out.push_back('\r');
        out.push_back(text[i]);
    }
    return out;
#else
    return text;
#endif
}

#ifdef _WIN32
void write_std_utf8(DWORD std_handle, const std::string &text_in) {
    if (text_in.empty()) return;
    std::string text = translate_newlines(text_in);
    HANDLE h = GetStdHandle(std_handle);
    DWORD mode;
    if (h != INVALID_HANDLE_VALUE && GetConsoleMode(h, &mode)) {
        std::wstring w = utf8_to_wide(text);
        DWORD written = 0;
        WriteConsoleW(h, w.data(), (DWORD)w.size(), &written, nullptr);
    } else {
        DWORD written = 0;
        WriteFile(h, text.data(), (DWORD)text.size(), &written, nullptr);
    }
}
#else
void write_std_utf8(int fd, const std::string &text_in) {
    if (text_in.empty()) return;
    std::string text = translate_newlines(text_in);
    size_t off = 0;
    while (off < text.size()) {
        ssize_t n = write(fd, text.data() + off, text.size() - off);
        if (n < 0) {
            if (errno == EINTR) continue;
            break;
        }
        off += (size_t)n;
    }
}
#endif

// -- fallback exec ---------------------------------------------------------------------

[[noreturn]] void fallback_exec(const std::vector<std::string> &argv, const fs::path &exe_path,
                                 const std::optional<fs::path> &repo_root,
                                 const std::string &reason) {
    trace("fallback: " + reason);
    fs::path exe_dir = exe_path.has_parent_path() ? exe_path.parent_path() : fs::current_path();

    if (!reason.empty()) set_env("AV_LAUNCHER_DAEMON_RESULT", reason);
    set_env("AV_LAUNCHER_EXE", exe_path.u8string());
    if (repo_root) set_env("AV_LAUNCHER_REPO", repo_root->u8string());

#ifdef _WIN32
    // A venv/install's `python.exe` lives one level UP from its `Scripts/` dir (where
    // `av-py.exe`/`av-native.exe` themselves are installed), not inside it -- easy to get
    // wrong (a real bug this exact function shipped once, found and fixed this session: an
    // earlier candidate list checked `exe_dir / "python.exe"`, which never exists, silently
    // fell through to a bare-PATH last resort that forgot to add `-m av_cli.launcher` at
    // all, so the fallback ran plain `python.exe --output json status` and Python's OWN
    // arg parser rejected `--output` as unrecognized).
    fs::path venv_root = exe_dir.has_parent_path() ? exe_dir.parent_path() : exe_dir;
    std::vector<std::pair<fs::path, bool>> candidates;
    if (auto av_python = get_env("AV_PYTHON")) candidates.emplace_back(fs::u8path(*av_python), false);
    candidates.emplace_back(exe_dir / "av-py.exe", false);
    candidates.emplace_back(venv_root / "python.exe", true);

    fs::path target;
    bool target_is_dash_m = false;
    for (const auto &[c, is_dash_m] : candidates) {
        std::error_code ec;
        if (fs::exists(c, ec)) {
            target = c;
            target_is_dash_m = is_dash_m;
            break;
        }
    }
    if (target.empty()) {
        target = "python.exe";  // PATH lookup, last resort
        target_is_dash_m = true;
    }

    std::wstring cmdline = L"\"" + target.wstring() + L"\"";
    if (target_is_dash_m) cmdline += L" -m av_cli.launcher";
    for (const auto &a : argv) {
        std::wstring wa = utf8_to_wide(a);
        // Minimal, conservative quoting -- good enough for the argv shapes this project's
        // own CLI actually takes (paths, flags, simple values); not a general
        // list2cmdline-equivalent implementation.
        bool needs_quote = wa.empty() || wa.find(L' ') != std::wstring::npos;
        cmdline += L" ";
        if (needs_quote) cmdline += L"\"" + wa + L"\"";
        else cmdline += wa;
    }

    STARTUPINFOW si{};
    si.cb = sizeof(si);
    PROCESS_INFORMATION pi{};
    std::vector<wchar_t> mutable_cmdline(cmdline.begin(), cmdline.end());
    mutable_cmdline.push_back(L'\0');
    BOOL ok = CreateProcessW(nullptr, mutable_cmdline.data(), nullptr, nullptr, TRUE, 0,
                              nullptr, nullptr, &si, &pi);
    if (!ok) {
        std::wcerr << L"av: could not find a Python interpreter to run av_cli (tried AV_PYTHON, "
                       L"av-py.exe, python.exe next to this launcher, and PATH). Set AV_PYTHON "
                       L"or ensure av-py is installed.\n";
        std::exit(1);
    }
    CloseHandle(pi.hThread);
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 1;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hProcess);
    std::exit((int)code);
#else
    // On POSIX, `av-py`/`python3` conventionally live in the SAME bin/ directory as this
    // launcher itself (a venv or install prefix's bin/, unlike Windows' Scripts/-vs-
    // install-root split) -- see setup.py's own placement of the compiled exe.
    std::vector<std::pair<fs::path, bool>> candidates;
    if (auto av_python = get_env("AV_PYTHON")) candidates.emplace_back(fs::u8path(*av_python), false);
    candidates.emplace_back(exe_dir / "av-py", false);
    candidates.emplace_back(exe_dir / "python3", true);
    candidates.emplace_back(exe_dir / "python", true);

    fs::path target;
    bool target_is_dash_m = false;
    for (const auto &[c, is_dash_m] : candidates) {
        std::error_code ec;
        if (fs::exists(c, ec)) {
            target = c;
            target_is_dash_m = is_dash_m;
            break;
        }
    }
    if (target.empty()) {
        target = "python3";  // PATH lookup via execvp, last resort
        target_is_dash_m = true;
    }

    std::vector<std::string> exec_argv_storage;
    exec_argv_storage.push_back(target.u8string());
    if (target_is_dash_m) {
        exec_argv_storage.push_back("-m");
        exec_argv_storage.push_back("av_cli.launcher");
    }
    for (const auto &a : argv) exec_argv_storage.push_back(a);

    std::vector<char *> exec_argv;
    exec_argv.reserve(exec_argv_storage.size() + 1);
    for (auto &s : exec_argv_storage) exec_argv.push_back(const_cast<char *>(s.c_str()));
    exec_argv.push_back(nullptr);

    // execvp REPLACES this process's image in place rather than forking a child and
    // waiting on it (the Windows side's CreateProcessW+WaitForSingleObject shape) -- no
    // second process, no wait step, and the exact same pid/stdio/exit-code semantics a
    // caller of the real `av-py`/`python -m av_cli.launcher` would see directly, since as
    // far as the OS and the calling shell are concerned this launcher process simply BECAME
    // that one. Deliberately not fork()+exec(): forking first would briefly duplicate this
    // process's own (small but nonzero) address space for no benefit, since nothing here
    // needs to keep running past this call either way.
    execvp(exec_argv[0], exec_argv.data());
    // execvp only returns on failure.
    std::fprintf(stderr,
                 "av: could not find a Python interpreter to run av_cli (tried AV_PYTHON, "
                 "av-py, python3/python next to this launcher, and PATH). Set AV_PYTHON "
                 "or ensure av-py is installed.\n");
    std::exit(1);
#endif
}

// ============================================================================
// run() -- the ENTIRE protocol/business logic, written once, called from either wmain()
// (Windows) or main() (POSIX) below. Neither entry point does anything except turn its own
// platform's raw argv into a std::vector<std::string> and hand it here.
// ============================================================================

int run(const std::vector<std::string> &argv) {
    fs::path exe_path = own_exe_path();

    // Exact `av --version` -- byte-identical to the Python path (fsutil.get_version()).
    if (argv.size() == 1 && argv[0] == "--version") {
        std::cout << "av " << AV_LAUNCHER_VERSION << "\n";
        return 0;
    }

    // Hidden diagnostic entry point for tests/test_launcher_native.py -- never used by real
    // invocations.
    if (argv.size() == 1 && argv[0] == "--av-launcher-info") {
        json info;
        info["version"] = AV_LAUNCHER_VERSION;
        info["protocol"] = 1;
        info["allowlist"] = kAllowedCommands;
        info["exe"] = exe_path.u8string();
        std::cout << info.dump() << "\n";
        return 0;
    }

    bool has_help = std::find(argv.begin(), argv.end(), "--help") != argv.end() ||
                    std::find(argv.begin(), argv.end(), "-h") != argv.end();
    std::optional<std::string> sub = first_subcommand(argv);

    if (has_help || !sub || !is_allowed(*sub)) {
        fallback_exec(argv, exe_path, std::nullopt, "not_eligible");
    }

    if (truthy_env("AV_NO_DAEMON")) {
        fallback_exec(argv, exe_path, std::nullopt, "disabled");
    }

    auto repo_root = find_repo_root();
    if (!repo_root) {
        fallback_exec(argv, exe_path, std::nullopt, "not_a_repo");
    }

    std::string exe_s = exe_path.u8string();
    std::string repo_s = repo_root->u8string();
    fs::path disc_path = discovery_file(exe_s, repo_s);

    std::ifstream disc_in(disc_path, std::ios::binary);
    if (!disc_in.good()) {
        fallback_exec(argv, exe_path, repo_root, "no_discovery_file");
    }
    json disc;
    try {
        disc_in >> disc;
    } catch (const json::exception &) {
        fallback_exec(argv, exe_path, repo_root, "malformed_discovery_file");
    }
    disc_in.close();

    if (!disc.is_object() || disc.value("protocol", -1) != 1 ||
        disc.value("cli_version", std::string()) != std::string(AV_LAUNCHER_VERSION)) {
        fallback_exec(argv, exe_path, repo_root, "version_skew");
    }

    std::string endpoint = disc.value("endpoint", std::string());
    std::string key_path_s = disc.value("key_path", std::string());
    if (endpoint.empty() || key_path_s.empty()) {
        fallback_exec(argv, exe_path, repo_root, "malformed_discovery_file");
    }

#ifdef _WIN32
    std::ifstream key_in(utf8_to_wide(key_path_s), std::ios::binary);
#else
    std::ifstream key_in(key_path_s, std::ios::binary);
#endif
    if (!key_in.good()) {
        fallback_exec(argv, exe_path, repo_root, "no_token");
    }
    std::string token((std::istreambuf_iterator<char>(key_in)), std::istreambuf_iterator<char>());
    while (!token.empty() && (token.back() == '\n' || token.back() == '\r' || token.back() == ' '))
        token.pop_back();

    auto conn = connect_daemon(endpoint);
    if (!conn) {
        fallback_exec(argv, exe_path, repo_root, "unreachable");
    }
    trace("connected to " + endpoint);

    std::error_code cwd_ec;
    fs::path cwd = fs::current_path(cwd_ec);

    std::string nonce = random_hex(16);
    json request;
    request["protocol"] = 1;
    request["cli_version"] = AV_LAUNCHER_VERSION;
    request["token"] = token;
    request["nonce"] = nonce;
    request["argv"] = argv;
    request["cwd"] = cwd.u8string();
    request["env"] = collect_allowlisted_env();
#ifdef _WIN32
    request["isatty"] = {{"stdout", _isatty(_fileno(stdout)) != 0}, {"stderr", _isatty(_fileno(stderr)) != 0}};
#else
    request["isatty"] = {{"stdout", isatty(STDOUT_FILENO) != 0}, {"stderr", isatty(STDERR_FILENO) != 0}};
#endif
    request["columns"] = nullptr;

    if (!send_frame(*conn, request)) {
        fallback_exec(argv, exe_path, repo_root, "unreachable");
    }
    trace("request sent, waiting for response");
    auto response = recv_frame(*conn);
    if (!response) {
        fallback_exec(argv, exe_path, repo_root, "unreachable");
    }

    if (response->contains("error")) {
        std::string err = response->value("error", std::string("unknown"));
        fallback_exec(argv, exe_path, repo_root, err);
    }

    std::string expected_mac = hmac_sha256_hex(token, nonce);
    std::string got_mac = response->value("server_nonce_mac", std::string());
    if (got_mac.size() != expected_mac.size() ||
        !std::equal(got_mac.begin(), got_mac.end(), expected_mac.begin())) {
        // Constant-time-ish comparison isn't the point here (both strings are already
        // known to the two parties, not secrets in transit) -- what matters is refusing to
        // trust or print anything from a response that didn't prove it came from the
        // daemon holding this token.
        fallback_exec(argv, exe_path, repo_root, "auth_failed");
    }

    trace("direct daemon round trip succeeded");
#ifdef _WIN32
    write_std_utf8(STD_OUTPUT_HANDLE, response->value("stdout", std::string()));
    write_std_utf8(STD_ERROR_HANDLE, response->value("stderr", std::string()));
#else
    write_std_utf8(STDOUT_FILENO, response->value("stdout", std::string()));
    write_std_utf8(STDERR_FILENO, response->value("stderr", std::string()));
#endif
    return response->value("exit_code", 1);
}

}  // namespace

#ifdef _WIN32
int wmain(int argc, wchar_t **wargv_raw) {
    // Deliberately no _setmode(_O_BINARY) here: std::cout's default Windows text-mode
    // translation (\n -> \r\n) is what makes the `--version`/`--av-launcher-info` paths
    // byte-identical to Python's own text-mode stdout. The daemon-response path never goes
    // through std::cout at all -- write_std_utf8() writes raw bytes via WriteFile/
    // WriteConsoleW, so it reproduces whatever bytes the daemon's own (already
    // Python-text-mode) stdout/stderr capture produced, unmodified.
    std::vector<std::string> argv;
    argv.reserve((size_t)argc > 0 ? (size_t)argc - 1 : 0);
    for (int i = 1; i < argc; ++i) argv.push_back(wide_to_utf8(wargv_raw[i]));
    return run(argv);
}
#else
int main(int argc, char **argv_raw) {
    std::vector<std::string> argv;
    argv.reserve((size_t)argc > 0 ? (size_t)argc - 1 : 0);
    for (int i = 1; i < argc; ++i) argv.push_back(std::string(argv_raw[i]));
    return run(argv);
}
#endif
