{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether-vault.secretName" . }}
  labels:
    {{- include "aether-vault.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.database.url | quote }}
  appDatabaseUrl: {{ .Values.database.appUrl | quote }}
  redisUrl: {{ .Values.redis.url | quote }}
  apiToken: {{ .Values.auth.apiToken | quote }}
  authUsers: {{ .Values.auth.authUsers | quote }}
{{- end }}
