apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-vault.fullname" . }}
  labels:
    {{- include "aether-vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
    - name: webui
      port: {{ .Values.service.webuiPort }}
      targetPort: webui
  selector:
    {{- include "aether-vault.selectorLabels" . | nindent 4 }}
