"""v1.3.0 (todo.md item 22): appends one row to the committed `development/perf-history.json`
and re-renders the trend table in `development/BENCHMARKS.md` — a release step the
maintainer runs LOCALLY (never from CI, matching this project's no-auto-commit CI policy;
see `tests/test_ci_policy.py`). Run this AFTER `av benchmark --markdown
development/BENCHMARKS.md` in the release checklist (see VERSIONING.md) — that command
fully overwrites BENCHMARKS.md, so this script's trend section needs to come after it, not
before.

Usage:
    python scripts/append_perf_history.py                      # capture + append + render
    python scripts/append_perf_history.py --dry-run             # print, don't write either file
    python scripts/append_perf_history.py --from-json PATH      # use an already-captured
                                                                   speedcheck JSON (e.g. the
                                                                   `test` workflow's uploaded
                                                                   artifact) instead of running
                                                                   the probes locally

The captured JSON shape (also what `--save-speedcheck-json` below writes, and what the
`test` CI job uploads as an artifact) is: {"date", "version", "os", "python", "probes":
{label: median_ms}}.
"""
import argparse
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "python"))

PERF_HISTORY_PATH = REPO_ROOT / "development" / "perf-history.json"
BENCHMARKS_PATH = REPO_ROOT / "development" / "BENCHMARKS.md"
TREND_START = "<!-- PERF-HISTORY:START (generated by scripts/append_perf_history.py — do not hand-edit between these markers) -->"
TREND_END = "<!-- PERF-HISTORY:END -->"

# The subset of speedcheck's probe labels rendered in the trend table — the full battery
# has ~15 probes; the table stays scannable by tracking the ones most likely to regress
# in a way that matters to an operator (not every internal micro-probe).
TRACKED_LABELS = [
    "Index.save()", "Index.load()", "load_config()", "iter_working_files()",
    "Storage stats", "semdiff.diff_trees()", "commit_staged()", "compute_status()", "log()",
]


def _project_version() -> str:
    # v1.3.0 (Probleme.md): a dev machine that has ever run more than one `pip install -e .`
    # / `pip wheel .` (e.g. this project's own Docker/packaging debugging) ends up with
    # MULTIPLE registered "aether-vault" distributions (a stale editable dist-info plus a
    # stale setup.py egg-info) whose METADATA was frozen at whatever version was checked out
    # at install time. `importlib.metadata.version("aether-vault")` picks between them by
    # sys.path order — which import-context-dependently returned "1.0.0" in one process and
    # "0.0.0" in another for the exact same git commit on this machine, silently poisoning a
    # release-version capture. `av_cli/_version.py` is regenerated by setuptools-scm on every
    # build (this project's own single source of truth for "what version is this checkout" —
    # see ui._get_version()'s identical, correct ordering) and is checked first for exactly
    # that reason; installed metadata is only a fallback for a source checkout that has never
    # been built at all.
    try:
        from av_cli._version import __version__
        return __version__
    except Exception:
        pass
    try:
        from importlib.metadata import version
        return version("aether-vault")
    except Exception:
        pass
    try:
        from setuptools_scm import get_version
        return get_version(root=str(REPO_ROOT))
    except Exception:
        return "unknown"


def capture_speedcheck_entry() -> dict:
    """Runs the same median-of-N sampled probe battery the perf gate (test_perf_gate.py)
    judges, and reduces it to one {label: median_ms} row for the history file."""
    import tempfile

    from av_cli import speedcheck
    from av_cli.main import iter_working_files, load_config

    with tempfile.TemporaryDirectory(prefix="av-perf-history-") as tmp:
        sampled = speedcheck.run_synthetic_probes_sampled(load_config, iter_working_files, Path(tmp))

    probes = {label: round(median_ms, 2) for label, _samples, median_ms, _budget, _cls in sampled}
    return {
        "date": datetime.now(timezone.utc).date().isoformat(),
        "version": _project_version(),
        "os": platform.platform(),
        "python": platform.python_version(),
        "probes": probes,
    }


def load_history() -> dict:
    if PERF_HISTORY_PATH.exists():
        return json.loads(PERF_HISTORY_PATH.read_text(encoding="utf-8"))
    return {"schema": "perf-history-1.0", "entries": []}


def _probe_value(probes: dict, tracked_label: str) -> float | None:
    """Probe labels carry a parenthetical fixture-size suffix that can change independently
    of the probe's identity (e.g. "Index.save() (500 entries)") — match by prefix, not
    exact equality, the same way test_perf_gate.py itself identifies probes."""
    for label, value in probes.items():
        if label.startswith(tracked_label):
            return value
    return None


def render_trend_table(history: dict) -> str:
    entries = history["entries"]
    if not entries:
        return f"{TREND_START}\n\n_No captures yet — run `python scripts/append_perf_history.py`._\n\n{TREND_END}"

    # Most recent N captures, oldest-first for a left-to-right reading of the trend.
    recent = entries[-10:]
    header = "| Date | Version | " + " | ".join(TRACKED_LABELS) + " |"
    sep = "|---|---|" + "---:|" * len(TRACKED_LABELS)
    rows = [header, sep]
    for e in recent:
        probes = e.get("probes", {})
        cells = []
        for l in TRACKED_LABELS:
            value = _probe_value(probes, l)
            cells.append(f"{value:.1f} ms" if value is not None else "—")
        rows.append(f"| {e.get('date', '?')} | {e.get('version', '?')} | " + " | ".join(cells) + " |")
    table = "\n".join(rows)
    note = (
        f"\n\n{len(entries)} capture(s) total, showing the most recent {len(recent)}. "
        "Machine varies across captures (see each entry's `os`/`python` in "
        "`development/perf-history.json`) — read this as a rough trend, not an apples-to-apples "
        "benchmark; `av test --speed` / the perf gate (`tests/test_perf_gate.py`) are the "
        "authoritative regression check for a single machine.\n"
    )
    return f"{TREND_START}\n\n## Perf history trend\n\n{table}{note}\n{TREND_END}"


def update_benchmarks_md(history: dict) -> str:
    trend_block = render_trend_table(history)
    text = BENCHMARKS_PATH.read_text(encoding="utf-8") if BENCHMARKS_PATH.exists() else ""
    if TREND_START in text and TREND_END in text:
        pre = text.split(TREND_START, 1)[0]
        post = text.split(TREND_END, 1)[1]
        return pre + trend_block + post
    # First run (or `av benchmark --markdown` just wiped the file, which is expected —
    # see this script's own module docstring on ordering): append the block at the end.
    sep = "\n\n" if text and not text.endswith("\n\n") else ""
    return text + sep + trend_block + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written; touch nothing.")
    parser.add_argument("--from-json", type=Path, default=None,
                        help="Use an already-captured speedcheck JSON instead of running the probes now.")
    parser.add_argument("--save-speedcheck-json", type=Path, default=None,
                        help="Also save the freshly captured entry as its own JSON file "
                             "(the shape the 'test' CI job uploads as an artifact).")
    args = parser.parse_args()

    entry = json.loads(args.from_json.read_text(encoding="utf-8")) if args.from_json else capture_speedcheck_entry()

    # --save-speedcheck-json is honored even under --dry-run: it writes a fresh, standalone
    # capture file, not the committed perf-history.json/BENCHMARKS.md --dry-run protects —
    # this is exactly what the `test` CI job uses to produce its uploaded artifact without
    # ever touching a tracked file (this project's CI never commits anything back to the repo).
    if args.save_speedcheck_json:
        args.save_speedcheck_json.write_text(json.dumps(entry, indent=2), encoding="utf-8")
        print(f"Saved speedcheck capture -> {args.save_speedcheck_json}")

    history = load_history()
    history["entries"].append(entry)
    rendered_md = update_benchmarks_md(history)

    print(f"Captured: {entry['date']} version={entry['version']} os={entry['os']} python={entry['python']}")
    print(f"Probes: {json.dumps(entry['probes'], indent=2)}")

    if args.dry_run:
        print(f"\n[DRY RUN] Would append to {PERF_HISTORY_PATH} and update {BENCHMARKS_PATH}.")
        return 0

    PERF_HISTORY_PATH.write_text(json.dumps(history, indent=2) + "\n", encoding="utf-8")
    BENCHMARKS_PATH.write_text(rendered_md, encoding="utf-8")
    print(f"\nAppended to {PERF_HISTORY_PATH} ({len(history['entries'])} entries total).")
    print(f"Updated trend table in {BENCHMARKS_PATH}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
